import {Card, Spacer, Text} from "@nextui-org/react";
import IPODetailsTable from "components/components/detailed-ipo/IPODetailsTable";
import IPOTables from "components/components/detailed-ipo/IPOTable";
import DownloadButtons from "components/components/download_buttons";
import Feedback from "components/components/feedback";
import Footer from "components/components/footer";
import Header from "components/components/header";
import {companies} from "components/components/ipo_details/ipo-details-1";
import imageMappings from "components/entities/imageMappings";
import {DM_Sans, Poppins} from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import {useRouter} from 'next/router'


const dm_sans = DM_Sans({
  weight: '700',
  subsets: ['latin']
})

const poppins = Poppins({
  weight: ['400', '500', '700', '900'],
  subsets: ['latin'],
})

export default function DetailedIPO() {
  const router = useRouter()
  const data = Number(router.query.id) ? companies[Number(router.query.id)] : companies[0]

  return (
    <>
      <Head>
        <title>{data.name} | checkIPO</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${poppins.className} bg-backgroundLight`}>
        <Header />
        <div className="flex flex-col items-center md:flex-row gap-30 md:gap-10 mx-30 pb-30 mt-30 md:items-center">
          <div className="w-full">
            <div className="flex justify-center items-center mb-30 min-h-[120px] relative bg-image-bg rounded-[15px]">
              <Image src={data.image} alt="Company Logo" fill style={{objectFit: 'contain'}} className="p-20" />
            </div>
          </div>
          <div className="flex flex-col items-center gap-10 md:ml-10 md:items-start md:max-w-[60%]">
            <Text className={`text-center md:text-left text-[30px] md:text-[42px] leading-[30px] md:leading-[42px] font-[700] ${dm_sans.className} md:max-w-[60%]`} css={{color: '$textDark'}}>{data.name}</Text>
            <Text className="text-[16px] leading-[24px] md:text-[20px] md:leading-[26px]" css={{color: '$textLight'}}>
              {data.description}
            </Text>
          </div>
        </div >
        <div className="flex flex-col gap-20 mx-20 navLogo:mx-30 md:mx-[80px]">
          <div>
            <Text className={`text-center md:text-left text-[24px] md:text-[32px] leading-[24px] md:leading-[32px] font-[700] mb-20 pl-10 ${dm_sans.className}`} css={{color: '$textDark'}}>IPO Details</Text>
            <IPODetailsTable ipoDetails={data.ipo_details} ipoTT={data.ipo_tentative_timetable} />
          </div>
          <div>
            <Text className={`text-center md:text-left text-[24px] md:text-[32px] leading-[24px] md:leading-[32px] font-[700] mb-20 pl-10 ${dm_sans.className}`} css={{color: '$textDark'}}>Company Financials</Text>
            <IPOTables companyFinances={data.company_financials} />
          </div>
        </div>

        <Spacer y={1.5} />

        <div className="flex flex-col gap-20 mx-20 navLogo:mx-30 md:mx-[80px]">
          <Text className={`text-center md:text-left text-[24px] md:text-[32px] leading-[24px] md:leading-[32px] font-[700] mb-20 pl-10 ${dm_sans.className}`} css={{color: '$textDark'}}>Internal Risks</Text>
          {data.risks.map((risk, idx) => {
            return (
              <Text key={idx} className="pl-20">{risk}</Text>
            )
          })}
        </div>

        <Spacer y={1.5} />

        <DownloadButtons drhp={data.drhp} rhp={data.rhp} />

        <Footer />
        <Feedback />
      </div>
    </>
  )
}