import {type NextPage} from "next";
import Head from "next/head";
import {Poppins} from 'next/font/google';
import DisclaimerView from "components/views/disclaimer";
import Feedback from "components/components/feedback";


const poppins = Poppins({
  weight: ['400', '500', '700', '900'],
  subsets: ['latin'],
})

const Disclaimer: NextPage = () => {
  return (
    <>
      <Head>
        <title>Disclaimer | checkIPO</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${poppins.className} font-[500] bg-backgroundLight`}>
        <DisclaimerView />
        <Feedback />
      </div>
    </>
  );
};

export default Disclaimer;
