import {type NextPage} from "next";
import Head from "next/head";

import {Poppins} from 'next/font/google';
import LandingView from "components/views/landing";
import IPOList from "components/views/ipo_list";
import FAQs from "components/views/faq";
import Footer from "components/components/footer";
import ContactUs from "components/components/contact_us";

const poppins = Poppins({
  weight: ['400', '500', '700', '900'],
  subsets: ['latin'],
})


const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>checkIPO</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${poppins.className} font-[500] bg-text bg-backgroundLight`}>
        <LandingView />
        <IPOList />
        <ContactUs />
        <FAQs />
        <Footer />
      </div>
    </>
  );
};

export default Home;
