import {type NextPage} from "next";
import Head from "next/head";
import {Poppins} from 'next/font/google';
import PrivacyView from "components/views/privacy";


const poppins = Poppins({
  weight: ['400', '500', '700', '900'],
  subsets: ['latin'],
})

const Privacy: NextPage = () => {
  return (
    <>
      <Head>
        <title>Privacy Policy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${poppins.className} font-[500]`}>
        <PrivacyView />
      </div>
    </>
  );
};

export default Privacy;
